### ISSUE TITLE
computing "Global score" throws ValueError when calling LiToy.py --review for the first time

### ISSUE THREAD

**Issue by sonofhypnos** [thiswillbeyourgithub/LiTOY-aka-List-that-Outlives-You#1]
Awesome Project! Just tried to get Litoy to work but there were some (surmountable) Issues when I tried running it. I still got it working so this is mostly for your information. I might make a pull request later on for the ones that annoy me.

- Initially the script did not run, because the log file was missing. on could check for an existing log file and otherwise add one.
- After I added the first entries, python threw a ValueError when I tried to "--review" my entries (I had already added 16 entries):
"Traceback (most recent call last):
  File "./LiTOY.py", line 495, in <module>
    print_stats(litoy.df, printing=False)
  File "/home/tassilo/repos/sonLiTOY/src/cli/cli.py", line 258, in print_stats
    table2.add_row(["Global score:", int(df_nvirg.gELO.mean()),
ValueError: cannot convert float NaN to integer"
- (I inserted ```except ValueError:\n pass``` into cli.py which worked as a fix for the above for me). The error wasn't thrown in later reviews.
- putting "qwerty" in my personal config did disable a and z working (see traceback below), but q was still quit and w was not recognized.
- a (and z) threw another error: "Traceback (most recent call last):
  File "./LiTOY.py", line 501, in <module>
    review_mode_cli(litoy)
  File "/home/tassilo/repos/sonLiTOY/src/cli/cli.py", line 502, in rev
    process_review_answer(keypress, entries[0], entries[1], mode,
  File "/home/tassilo/repos/sonLiTOY/src/backend/backend.py", line 304
    keypress = round(int(keypress) / 6 * 5, 2)  # resize value from 1-
ValueError: invalid literal for int() with base 10: 'a'"

**Comment by thiswillbeyourgithub** [comment]
Hi!

Thanks a lot for the interest and the kind word.

Good catch for those bugs. I actually was using a separate branch and merged it just before "publicizing" and apparently I missed some things in the merge.

* I fixed the missing log  file : fa39eaf5dfa6502320b2fb782494b00bb19111f0
* I added the workaround to missing global values : 8ecdbc90d8a0e4a40227f619e69e975a92cd628a
* I removed the "keyboard" option entirely and added both azerty and qwerty support by default : 671f7677cfd2fb12d1257d375cf168c2589f6502

I recommand you pull -f the changes as I changed a few other things.

There are lots of other bugs probably but it's kinda hard to spot them when I'm the only user with my own habits so thanks a lot for reporting :)
