### ISSUE TITLE
Not enough data points to start reviewing: variance requires at least two data points

### ISSUE THREAD

**Issue by bartbussmann** [thiswillbeyourgithub/LiTOY-aka-List-that-Outlives-You#2]
I was just trying out LiTOY and added my first 10 items to my database. Now, when I run:

`python3.8 LiTOY.py --db database.json --review` I get the following error:

Not enough data points to start reviewing: variance requires at least two data points.

Is this a bug or am I doing something wrong?

**Comment by thiswillbeyourgithub** [comment]
Glad you fixed your problem :) Don't hesitate to offer me suggestion, maybe the documentation wasn't clear ? etc

Have a nice day!
