### ISSUE TITLE
Python 3.8 installation on Ubuntu Issues

### ISSUE THREAD

**Issue by rajlego** [thiswillbeyourgithub/LiTOY-aka-List-that-Outlives-You#3]
I found that I had to follow these instructions to get pip3.8:
https://stackoverflow.com/a/69864941/7800469 (also gets python3.8)

I still had errors compiling via pip install -r requirements.txt; I had to do sudo apt install python3.8-dev

(this isn't an issue since I got it working but I expect this to be a confusing and annoying problem for someone with less linux experience than me)

**Comment by thiswillbeyourgithub** [comment]
Okay thanks!
